CREATE TABLE IF NOT EXISTS CHATS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  metadata TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS MESSAGES(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER NOT NULL,
  metadata TEXT NOT NULL,
  responder TEXT NOT NULL, -- 'user', 'assistant', or 'system'
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(chat_id) REFERENCES CHATS(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MESSAGE_ASSETS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  metadata TEXT NOT NULL,
  msg_id INTEGER NOT NULL,
  asset_type INTEGER NOT NULL, -- used to diff between audio, image, etc
  data BLOB NOT NULL,
  FOREIGN KEY(msg_id) REFERENCES MESSAGES(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS INDEX_MSG_CHAT_MAP ON MESSAGES(chat_id, responder, created_at);
CREATE INDEX IF NOT EXISTS INDEX_ASSET_MSG_MAP ON MESSAGE_ASSETS(msg_id, asset_type);

CREATE VIRTUAL TABLE MESSAGES_SEARCH USING fts5(
  content,
  content = 'MESSAGES',
  content_rowid = 'id',
  tokenize = 'porter'
);

-- Sync Insert
CREATE TRIGGER messages_ai AFTER INSERT ON MESSAGES 
BEGIN
  INSERT INTO MESSAGES_SEARCH(rowid, content) VALUES (new.id, new.content);
END;

-- Sync Delete
CREATE TRIGGER messages_ad BEFORE DELETE ON MESSAGES 
BEGIN
  INSERT INTO MESSAGES_SEARCH(MESSAGES_SEARCH, rowid, content) VALUES('delete', old.id, old.content);
END;

-- Sync Update
CREATE TRIGGER messages_au AFTER UPDATE ON MESSAGES BEGIN
  INSERT INTO MESSAGES_SEARCH(MESSAGES_SEARCH, rowid, content) VALUES('delete', old.id, old.content);
  INSERT INTO MESSAGES_SEARCH(rowid, content) VALUES (new.id, new.content);
END;